---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: latest
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/ansible/ansible-lint.git
  rev: latest
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
