---
container_name: openbooks

dashboard_url: "http://openbooks.{{ host_local }}/"

health_url: "http://{{ ansible_default_ipv4.address }}:3000/http://openbooks.{{ host_local }}"

homer_category: media

dashboard_name: "OpenBooks"