---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "evanbuss/openbooks"
    pull: yes
    networks:
      - name: swag_internal_macvlan
        ipv4_address: 10.0.0.9
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
    restart_policy: unless-stopped
