- name: Restart netfilter-persistent
  service:
    name: netfilter-persistent
    state: restarted

- name: Restart crowdsec
  service:
    name: crowdsec
    state: restarted


- name: Restart prometheus
  service:
    name: prometheus
    state: restarted
