---
- name: Install netfilters-persistent
  package:
    name: netfilter-persistent
    state: present

- name: Log port scanning attempts (iptables)
  iptables:
    chain: INPUT
    match: conntrack
    ctstate: NEW
    comment: "Log new connections"
    jump: LOG

- name: Persist the port scanning rule (iptables)
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4
  notify:
    - Restart netfilter-persistent