---
container_name: vaultwarden

dashboard_url: "https://{{ subdomains['vaultwarden'] }}.{{ host }}"

homer_category: services

dashboard_name: Vaultwarden

health_url: "http://{{ ansible_default_ipv4.address }}:3000/https://{{ subdomains['vaultwarden'] }}.{{ host }}"